/*
 * ICC PROJECT
 *
 * Welcome to use ICC product
 *
 * API version: 1.0.0
 * Contact: 
 * Generated by: lcy
 */

package main

import (
	//"go_server/mysql"
	//redis2 "go_server/redis"
	sw "go_server/service"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")
	//InitLog()
	//sql := mysql.GetMysql(USERNAME, PASSWORD, NETWORK, SERVER, PORT, DATABASE)
	//redis := redis2.GetRedis(RedisIp, RedisPort, ExpireTime)
	//redis.TestRedis()
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":5000", router))
}



