/*
 * ICC PROJECT
 *
 * Welcome to use ICC product
 *
 * API version: 1.0.0
 * Contact: 
 * Generated by: lcy
 */

package main

import (
	sw "go_server/service"
	"log"
	"net/http"
	"os"
	"time"
)

var loger *log.Logger

func init() {
	filename := time.Now().Format("2006-01-02")
	file := "./log/" +filename + ".txt"
	logFile, err := os.OpenFile(file, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0766)
	if err != nil {
		panic(err)
	}
	loger = log.New(logFile, "[qSkiptool]",log.LstdFlags | log.Lshortfile | log.LUTC) // 将文件设置为loger作为输出
	return
}

func main() {
	loger.Println("Server started; Listening on 8000")
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8000", router))
}


